name: Check
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - '**/src/**'
      - '**.gradle.kts'
      - 'gradle.properties'
  pull_request:
    branches:
      - 'main'
      - 'test/**'
      - 'feature/**'
    paths:
      - '**/src/**'
      - '**.gradle.kts'
      - 'gradle.properties'

jobs:
  build-agent:
    strategy:
      fail-fast: false
      matrix:
        config:
          - { os: ubuntu-latest, preset: linuxX64 }
          - { os: windows-latest, preset: mingwX64 }
          - { os: macos-latest, preset: macosX64 }
    runs-on: ${{ matrix.config.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 8.0
          distribution: 'corretto'
      - if: matrix.config.preset == 'linuxX64' || matrix.config.preset == 'macosX64'
        run: chmod +x ${{ github.workspace }}/gradlew
      - if: matrix.config.preset == 'linuxX64' || matrix.config.preset == 'macosX64'
        run: chmod +x ${{ github.workspace }}/setup-shared-libs.sh
      - if: matrix.config.preset == 'linuxX64'
        run: sudo apt-get install -y libtinfo5
      - if: matrix.config.preset == 'linuxX64' || matrix.config.preset == 'macosX64'
        run: ${{ github.workspace }}/setup-shared-libs.sh
      - if: matrix.config.preset == 'mingwX64'
        run: ${{ github.workspace }}/setup-shared-libs.bat
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 7.4.2
      - run: gradle :test-agent:runtimeJar :test-agent:build
      - name: Upload agent binary
        uses: actions/upload-artifact@master
        with:
          name: agent-binary-${{matrix.config.preset}}
          path: |
            test-agent/build/bin/**/*.dll
            test-agent/build/bin/**/*.so
            test-agent/build/bin/**/*.dylib
      - name: Upload agent jar
        uses: actions/upload-artifact@master
        with:
          name: agent-jar-${{matrix.config.preset}}
          path: test-agent/build/libs/drill-runtime.jar
  servlet-tests:
    needs: build-agent
    strategy:
      fail-fast: false
      matrix:
        config:
          - { os: ubuntu-latest, preset: linuxX64 }
          - { os: windows-latest, preset: mingwX64 }
          - { os: macos-latest, preset: macosX64 }
        envVersions:
          - { testModule: 'tests:web-frameworks:servlet-4-jetty-9', javaVersion: 8.0, distribution: 'corretto', gradleVersion: '7.4.2' }
          - { testModule: 'tests:web-frameworks:servlet-4-jetty-9', javaVersion: 17.0, distribution: 'corretto', gradleVersion: '7.4.2' }
          - { testModule: 'tests:web-frameworks:servlet-4-tomcat-9', javaVersion: 8.0, distribution: 'corretto', gradleVersion: '7.4.2' }
          - { testModule: 'tests:web-frameworks:servlet-4-tomcat-9', javaVersion: 17.0, distribution: 'corretto', gradleVersion: '7.4.2' }
          - { testModule: 'tests:web-frameworks:servlet-5-tomcat-10', javaVersion: 11.0, distribution: 'corretto', gradleVersion: '7.4.2' }
          - { testModule: 'tests:web-frameworks:servlet-5-tomcat-10', javaVersion: 17.0, distribution: 'corretto', gradleVersion: '7.4.2' }
          - { testModule: 'tests:web-frameworks:servlet-5-jetty-11', javaVersion: 17.0, distribution: 'corretto', gradleVersion: '7.4.2' }
          - { testModule: 'tests:web-frameworks:servlet-5-undertow-2', javaVersion: 11.0, distribution: 'corretto', gradleVersion: '7.4.2' }
          - { testModule: 'tests:web-frameworks:servlet-5-undertow-2', javaVersion: 17.0, distribution: 'corretto', gradleVersion: '7.4.2' }
          - { testModule: 'tests:web-frameworks:servlet-6-tomcat-11', javaVersion: 17.0, distribution: 'corretto', gradleVersion: '7.4.2' }
    uses: ./.github/workflows/template.yml
    with:
      os: ${{ matrix.config.os }}
      preset: ${{ matrix.config.preset }}
      javaVersion: ${{ matrix.envVersions.javaVersion }}
      distribution: ${{ matrix.envVersions.distribution }}
      testModule: ${{ matrix.envVersions.testModule }}
      gradleVersion: ${{ matrix.envVersions.gradleVersion }}
  web-framework-tests:
    needs: build-agent
    strategy:
      fail-fast: false
      matrix:
        config:
          - { os: ubuntu-latest, preset: linuxX64 }
          - { os: windows-latest, preset: mingwX64 }
          - { os: macos-latest, preset: macosX64 }
        envVersions:
          # Spring 1.5.22 (Only Spring MVC, WebFlux appears from 2.X version of Spring Boot)
          - { javaVersion: 8.0, distribution: 'corretto', testModule: 'tests:web-frameworks:spring-mvc-1.5-jetty', gradleVersion: '7.4.2' }
          - { javaVersion: 8.0, distribution: 'corretto', testModule: 'tests:web-frameworks:spring-mvc-1.5-tomcat', gradleVersion: '7.4.2' }
          - { javaVersion: 8.0, distribution: 'corretto', testModule: 'tests:web-frameworks:spring-mvc-1.5-undertow', gradleVersion: '7.4.2' }
          - { javaVersion: 8.0, distribution: 'temurin', testModule: 'tests:web-frameworks:spring-mvc-1.5-jetty', gradleVersion: '7.4.2' }
          - { javaVersion: 8.0, distribution: 'zulu', testModule: 'tests:web-frameworks:spring-mvc-1.5-jetty', gradleVersion: '7.4.2' }

          - { javaVersion: 11.0, distribution: 'corretto', testModule: 'tests:web-frameworks:spring-mvc-1.5-jetty', gradleVersion: '7.4.2' }
          - { javaVersion: 11.0, distribution: 'corretto', testModule: 'tests:web-frameworks:spring-mvc-1.5-tomcat', gradleVersion: '7.4.2' }
          - { javaVersion: 11.0, distribution: 'corretto', testModule: 'tests:web-frameworks:spring-mvc-1.5-undertow', gradleVersion: '7.4.2' }
          - { javaVersion: 11.0, distribution: 'temurin', testModule: 'tests:web-frameworks:spring-mvc-1.5-jetty', gradleVersion: '7.4.2' }
          - { javaVersion: 11.0, distribution: 'zulu', testModule: 'tests:web-frameworks:spring-mvc-1.5-jetty', gradleVersion: '7.4.2' }

          - { javaVersion: 17.0, distribution: 'corretto', testModule: 'tests:web-frameworks:spring-mvc-1.5-jetty', gradleVersion: '7.4.2' }
          - { javaVersion: 17.0, distribution: 'corretto', testModule: 'tests:web-frameworks:spring-mvc-1.5-tomcat', gradleVersion: '7.4.2' }
          - { javaVersion: 17.0, distribution: 'corretto', testModule: 'tests:web-frameworks:spring-mvc-1.5-undertow', gradleVersion: '7.4.2' }
          - { javaVersion: 17.0, distribution: 'temurin', testModule: 'tests:web-frameworks:spring-mvc-1.5-jetty', gradleVersion: '7.4.2' }
          - { javaVersion: 17.0, distribution: 'zulu', testModule: 'tests:web-frameworks:spring-mvc-1.5-jetty', gradleVersion: '7.4.2' }
          - { javaVersion: 17.0, distribution: 'oracle', testModule: 'tests:web-frameworks:spring-mvc-1.5-jetty', gradleVersion: '7.4.2' }

          # Spring 2.7.18
          - { javaVersion: 8.0, distribution: 'corretto', testModule: 'tests:web-frameworks:spring-mvc-2.7-jetty', gradleVersion: '7.4.2' }
          - { javaVersion: 8.0, distribution: 'corretto', testModule: 'tests:web-frameworks:spring-mvc-2.7-tomcat', gradleVersion: '7.4.2' }
          - { javaVersion: 8.0, distribution: 'corretto', testModule: 'tests:web-frameworks:spring-mvc-2.7-undertow', gradleVersion: '7.4.2' }
          - { javaVersion: 8.0, distribution: 'corretto', testModule: 'tests:web-frameworks:spring-webflux-2.7-jetty', gradleVersion: '7.4.2' }
          - { javaVersion: 8.0, distribution: 'corretto', testModule: 'tests:web-frameworks:spring-webflux-2.7-netty', gradleVersion: '7.4.2' }
          - { javaVersion: 8.0, distribution: 'corretto', testModule: 'tests:web-frameworks:spring-webflux-2.7-tomcat', gradleVersion: '7.4.2' }
          - { javaVersion: 8.0, distribution: 'corretto', testModule: 'tests:web-frameworks:spring-webflux-2.7-undertow', gradleVersion: '7.4.2' }

          - { javaVersion: 11.0, distribution: 'corretto', testModule: 'tests:web-frameworks:spring-mvc-2.7-jetty', gradleVersion: '7.4.2' }
          - { javaVersion: 11.0, distribution: 'corretto', testModule: 'tests:web-frameworks:spring-mvc-2.7-tomcat', gradleVersion: '7.4.2' }
          - { javaVersion: 11.0, distribution: 'corretto', testModule: 'tests:web-frameworks:spring-mvc-2.7-undertow', gradleVersion: '7.4.2' }
          - { javaVersion: 11.0, distribution: 'corretto', testModule: 'tests:web-frameworks:spring-webflux-2.7-jetty', gradleVersion: '7.4.2' }
          - { javaVersion: 11.0, distribution: 'corretto', testModule: 'tests:web-frameworks:spring-webflux-2.7-netty', gradleVersion: '7.4.2' }
          - { javaVersion: 11.0, distribution: 'corretto', testModule: 'tests:web-frameworks:spring-webflux-2.7-tomcat', gradleVersion: '7.4.2' }
          - { javaVersion: 11.0, distribution: 'corretto', testModule: 'tests:web-frameworks:spring-webflux-2.7-undertow', gradleVersion: '7.4.2' }

          - { javaVersion: 17.0, distribution: 'corretto', testModule: 'tests:web-frameworks:spring-mvc-2.7-jetty', gradleVersion: '7.4.2' }
          - { javaVersion: 17.0, distribution: 'corretto', testModule: 'tests:web-frameworks:spring-mvc-2.7-tomcat', gradleVersion: '7.4.2' }
          - { javaVersion: 17.0, distribution: 'corretto', testModule: 'tests:web-frameworks:spring-mvc-2.7-undertow', gradleVersion: '7.4.2' }
          - { javaVersion: 17.0, distribution: 'corretto', testModule: 'tests:web-frameworks:spring-webflux-2.7-jetty', gradleVersion: '7.4.2' }
          - { javaVersion: 17.0, distribution: 'corretto', testModule: 'tests:web-frameworks:spring-webflux-2.7-netty', gradleVersion: '7.4.2' }
          - { javaVersion: 17.0, distribution: 'corretto', testModule: 'tests:web-frameworks:spring-webflux-2.7-tomcat', gradleVersion: '7.4.2' }
          - { javaVersion: 17.0, distribution: 'corretto', testModule: 'tests:web-frameworks:spring-webflux-2.7-undertow', gradleVersion: '7.4.2' }
          - { javaVersion: 17.0, distribution: 'oracle', testModule: 'tests:web-frameworks:spring-webflux-2.7-netty', gradleVersion: '7.4.2' }
          - { javaVersion: 17.0, distribution: 'temurin', testModule: 'tests:web-frameworks:spring-webflux-2.7-netty', gradleVersion: '7.4.2' }
          - { javaVersion: 17.0, distribution: 'zulu', testModule: 'tests:web-frameworks:spring-webflux-2.7-netty', gradleVersion: '7.4.2' }
          # Spring 3.1.9
          - { javaVersion: 17.0, distribution: 'corretto', testModule: 'tests:web-frameworks:spring-mvc-3.1-jetty', gradleVersion: '7.4.2' }
          - { javaVersion: 17.0, distribution: 'corretto', testModule: 'tests:web-frameworks:spring-mvc-3.1-tomcat', gradleVersion: '7.4.2' }
          - { javaVersion: 17.0, distribution: 'corretto', testModule: 'tests:web-frameworks:spring-mvc-3.1-undertow', gradleVersion: '7.4.2' }
          - { javaVersion: 17.0, distribution: 'corretto', testModule: 'tests:web-frameworks:spring-webflux-3.1-jetty', gradleVersion: '7.4.2' }
          - { javaVersion: 17.0, distribution: 'corretto', testModule: 'tests:web-frameworks:spring-webflux-3.1-netty', gradleVersion: '7.4.2' }
          - { javaVersion: 17.0, distribution: 'corretto', testModule: 'tests:web-frameworks:spring-webflux-3.1-tomcat', gradleVersion: '7.4.2' }
          - { javaVersion: 17.0, distribution: 'corretto', testModule: 'tests:web-frameworks:spring-webflux-3.1-undertow', gradleVersion: '7.4.2' }
          - { javaVersion: 21.0, distribution: 'corretto', testModule: 'tests:web-frameworks:spring-webflux-3.1-jetty', gradleVersion: '8.5', kotlinVersion: '1.9.20' }
    uses: ./.github/workflows/template.yml
    with:
      os: ${{ matrix.config.os }}
      preset: ${{ matrix.config.preset }}
      javaVersion: ${{ matrix.envVersions.javaVersion }}
      distribution: ${{ matrix.envVersions.distribution }}
      testModule: ${{ matrix.envVersions.testModule }}
      gradleVersion: ${{ matrix.envVersions.gradleVersion }}
  web-server-tests:
    needs: build-agent
    strategy:
      fail-fast: false
      matrix:
        config:
          - { os: ubuntu-latest, preset: linuxX64 }
          - { os: windows-latest, preset: mingwX64 }
          - { os: macos-latest, preset: macosX64 }
        envVersions:
          # Web Servers:
          # Jetty
          - { javaVersion: 11.0, distribution: 'corretto', testModule: 'tests:web-servers:jetty-10.0', gradleVersion: '7.4.2' }
          - { javaVersion: 17.0, distribution: 'corretto', testModule: 'tests:web-servers:jetty-10.0', gradleVersion: '7.4.2' }
          - { javaVersion: 21.0, distribution: 'corretto', testModule: 'tests:web-servers:jetty-10.0', gradleVersion: '8.5', kotlinVersion: '1.9.20' }
          # Netty:
          - { javaVersion: 8.0, distribution: 'corretto', testModule: 'tests:web-servers:netty-4.1', gradleVersion: '7.4.2' }
          - { javaVersion: 11.0, distribution: 'corretto', testModule: 'tests:web-servers:netty-4.1', gradleVersion: '7.4.2' }
          - { javaVersion: 17.0, distribution: 'corretto', testModule: 'tests:web-servers:netty-4.1', gradleVersion: '7.4.2' }
          - { javaVersion: 21.0, distribution: 'corretto', testModule: 'tests:web-servers:netty-4.1', gradleVersion: '8.5', kotlinVersion: '1.9.20' }
          # Tomcat:
          - { javaVersion: 11.0, distribution: 'corretto', testModule: 'tests:web-servers:tomcat-10.1', gradleVersion: '7.4.2' }
          - { javaVersion: 17.0, distribution: 'corretto', testModule: 'tests:web-servers:tomcat-11.0', gradleVersion: '7.4.2' }
          - { javaVersion: 21.0, distribution: 'corretto', testModule: 'tests:web-servers:tomcat-11.0', gradleVersion: '8.5', kotlinVersion: '1.9.20' }
          # Undertow:
          - { javaVersion: 11.0, distribution: 'corretto', testModule: 'tests:web-servers:undertow-2.3', gradleVersion: '7.4.2' }
          - { javaVersion: 17.0, distribution: 'corretto', testModule: 'tests:web-servers:undertow-2.3', gradleVersion: '7.4.2' }
          - { javaVersion: 21.0, distribution: 'corretto', testModule: 'tests:web-servers:undertow-2.3', gradleVersion: '8.5', kotlinVersion: '1.9.20' }
    uses: ./.github/workflows/template.yml
    with:
      os: ${{ matrix.config.os }}
      preset: ${{ matrix.config.preset }}
      javaVersion: ${{ matrix.envVersions.javaVersion }}
      distribution: ${{ matrix.envVersions.distribution }}
      testModule: ${{ matrix.envVersions.testModule }}
      gradleVersion: ${{ matrix.envVersions.gradleVersion }}

  http-client-tests:
    needs: build-agent
    strategy:
      fail-fast: false
      matrix:
        config:
          - { os: ubuntu-latest, preset: linuxX64 }
          - { os: windows-latest, preset: mingwX64 }
          - { os: macos-latest, preset: macosX64 }
        envVersions:
          # Http Clients:
          # URLConnection
          - { javaVersion: 8.0, distribution: 'corretto', testModule: 'tests:http-clients:urlconnection', gradleVersion: '7.4.2' }
          - { javaVersion: 17.0, distribution: 'corretto', testModule: 'tests:http-clients:urlconnection', gradleVersion: '7.4.2' }
          # Apache HttpClient
          - { javaVersion: 8.0, distribution: 'corretto', testModule: 'tests:http-clients:apache-http-client-4.5', gradleVersion: '7.4.2' }
          - { javaVersion: 17.0, distribution: 'corretto', testModule: 'tests:http-clients:apache-http-client-4.5', gradleVersion: '7.4.2' }
          - { javaVersion: 8.0, distribution: 'corretto', testModule: 'tests:http-clients:apache-http-client-5.3', gradleVersion: '7.4.2' }
          - { javaVersion: 17.0, distribution: 'corretto', testModule: 'tests:http-clients:apache-http-client-5.3', gradleVersion: '7.4.2' }
          # OkHttp Client
          - { javaVersion: 8.0, distribution: 'corretto', testModule: 'tests:http-clients:okhttp-client-3.12', gradleVersion: '7.4.2' }
          - { javaVersion: 17.0, distribution: 'corretto', testModule: 'tests:http-clients:okhttp-client-3.12', gradleVersion: '7.4.2' }
          - { javaVersion: 8.0, distribution: 'corretto', testModule: 'tests:http-clients:okhttp-client-3.14', gradleVersion: '7.4.2' }
          - { javaVersion: 17.0, distribution: 'corretto', testModule: 'tests:http-clients:okhttp-client-3.14', gradleVersion: '7.4.2' }
          - { javaVersion: 8.0, distribution: 'corretto', testModule: 'tests:http-clients:okhttp-client-4.12', gradleVersion: '7.4.2', kotlinVersion: '1.9.20' }
          - { javaVersion: 17.0, distribution: 'corretto', testModule: 'tests:http-clients:okhttp-client-4.12', gradleVersion: '7.4.2', kotlinVersion: '1.9.20' }
          # Spring RestTemplate
          - { javaVersion: 8.0, distribution: 'corretto', testModule: 'tests:http-clients:spring-resttemplate-4.3', gradleVersion: '7.4.2' }
          - { javaVersion: 17.0, distribution: 'corretto', testModule: 'tests:http-clients:spring-resttemplate-4.3', gradleVersion: '7.4.2' }
          - { javaVersion: 8.0, distribution: 'corretto', testModule: 'tests:http-clients:spring-resttemplate-5.3', gradleVersion: '7.4.2' }
          - { javaVersion: 17.0, distribution: 'corretto', testModule: 'tests:http-clients:spring-resttemplate-5.3', gradleVersion: '7.4.2' }
          # Spring WebClient
          - { javaVersion: 8.0, distribution: 'corretto', testModule: 'tests:http-clients:spring-webclient-5.3', gradleVersion: '7.4.2' }
          - { javaVersion: 17.0, distribution: 'corretto', testModule: 'tests:http-clients:spring-webclient-5.3', gradleVersion: '7.4.2' }
          - { javaVersion: 17.0, distribution: 'corretto', testModule: 'tests:http-clients:spring-webclient-6.1', gradleVersion: '7.4.2' }
          # Feign Client
          - { javaVersion: 8.0, distribution: 'corretto', testModule: 'tests:http-clients:feign-client-13', gradleVersion: '7.4.2' }
          - { javaVersion: 17.0, distribution: 'corretto', testModule: 'tests:http-clients:feign-client-13', gradleVersion: '7.4.2' }
    uses: ./.github/workflows/template.yml
    with:
      os: ${{ matrix.config.os }}
      preset: ${{ matrix.config.preset }}
      javaVersion: ${{ matrix.envVersions.javaVersion }}
      distribution: ${{ matrix.envVersions.distribution }}
      testModule: ${{ matrix.envVersions.testModule }}
      gradleVersion: ${{ matrix.envVersions.gradleVersion }}
