name: Check
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - '**/src/**'
      - '**.gradle.kts'
      - 'gradle.properties'
  pull_request:
    branches:
      - 'main'
    paths:
      - '**/src/**'
      - '**.gradle.kts'
      - 'gradle.properties'

jobs:
  check:
    strategy:
      fail-fast: false
      matrix:
        config:
          - { os: ubuntu-latest, preset: linuxX64 }
          - { os: windows-latest, preset: mingwX64 }
          - { os: macos-latest, preset: macosX64 }
        javaVersion:
          - { version: 8.0, distribution: 'zulu' }
          - { version: 8.0, distribution: 'temurin' }
          - { version: 8.0, distribution: 'corretto' }
          - { version: 11.0, distribution: 'zulu' }
          - { version: 11.0, distribution: 'temurin' }
          - { version: 11.0, distribution: 'corretto' }
          - { version: 17.0, distribution: 'zulu' }
          - { version: 17.0, distribution: 'temurin' }
          - { version: 17.0, distribution: 'corretto' }
          - { version: 17.0, distribution: 'oracle' }
    runs-on: ${{ matrix.config.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.javaVersion.version }}
          distribution: ${{ matrix.javaVersion.distribution }}
      - if: matrix.config.preset == 'linuxX64' || matrix.config.preset == 'macosX64'
        run: |
          if echo "${{ matrix.javaVersion.version }}" | grep -q "^17.0"; then
            echo "Using java17.gradle.properties"
            echo "PROPERTIES_FILE=java17.gradle.properties" >> $GITHUB_ENV
          fi
      - if: matrix.config.preset == 'mingwX64'
        shell: pwsh
        run: |
          if ("${{ matrix.javaVersion.version }}" -eq "17.0") {
            Write-Output "Using java17.gradle.properties"
            echo "PROPERTIES_FILE=java17.gradle.properties" | Out-File -Append -FilePath $env:GITHUB_ENV -Encoding utf8
          }
      - uses: gradle/wrapper-validation-action@v1
      - if: matrix.config.preset == 'linuxX64' || matrix.config.preset == 'macosX64'
        run: chmod +x ${{ github.workspace }}/gradlew
      - if: matrix.config.preset == 'linuxX64' || matrix.config.preset == 'macosX64'
        run: chmod +x ${{ github.workspace }}/setup-shared-libs.sh
      - if: matrix.config.preset == 'linuxX64'
        run: sudo apt-get install -y libtinfo5
      - if: matrix.config.preset == 'linuxX64' || matrix.config.preset == 'macosX64'
        run: ${{ github.workspace }}/setup-shared-libs.sh
      - if: matrix.config.preset == 'mingwX64'
        run: ${{ github.workspace }}/setup-shared-libs.bat
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: check