name: Run test
on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      preset:
        required: true
        type: string
      javaVersion:
        required: true
        type: string
      distribution:
        required: true
        type: string
      testModule:
        required: true
        type: string
      gradleVersion:
        required: true
        type: string
      kotlinVersion:
        required: false
        type: string
      testReport:
        required: false
        type: string

jobs:
  run-tests:
    runs-on: ${{ inputs.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Download .drill folder
        uses: actions/download-artifact@v4
        with:
          name: drill-agents-${{ inputs.os }}
          path: ~/.drill/agents
      - name: List .drill files
        run: ls ~/.drill/agents
      - name: Set-up kotlin version
        if: inputs.javaVersion == '21' || inputs.kotlinVersion != ''
        run: echo "kotlinVersion=${{ inputs.kotlinVersion }}" >> $GITHUB_ENV
        shell: bash
      - uses: actions/setup-java@v3
        with:
          java-version: ${{ inputs.javaVersion }}
          distribution: ${{ inputs.distribution }}
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: ${{ inputs.gradleVersion }}
      - name: Run tests
        run: gradle ${{ inputs.testModule }}:check "-Dtest-agent.binaries=${{ github.workspace }}/agent" --info
      - name: Upload test report
        if: failure() && inputs.testReport != ''
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: /home/runner/work/internal-compatibility-matrix-tests/internal-compatibility-matrix-tests/${{ inputs.testReport }}/build/reports/tests/test
