name: Compatibility Matrix Tests

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  download-agents:
    runs-on: ${{ matrix.os }}
    env:
      GH_USER_TOKEN: ${{ secrets.GH_USER_TOKEN }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, windows-latest, macos-12]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 17.0
          distribution: corretto
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 7.4.2
      - name: Download Drill4J Agents
        run: gradle drillDownloadAgents --info
      - name: List .drill files
        run: ls ~/.drill/agents
      - name: Upload .drill folder as artifact
        uses: actions/upload-artifact@v4
        with:
          name: drill-agents-${{ matrix.os }}
          path: ~/.drill/agents
          if-no-files-found: error
  test_matrix:
    needs: download-agents
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-12]
        java-version: [8, 11, 17, 21]
    steps:
      - name: Download .drill folder
        uses: actions/download-artifact@v4
        with:
          name: drill-agents-${{ matrix.os }}
          path: ~/.drill/agents

      - name: Set up Java ${{ matrix.java-version }}
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: ${{ matrix.java-version }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Determine Kotlin version for Java 21 and greater
        id: determine-kotlin
        if: matrix.java-version >= 21
        run: echo "kotlin-version=1.9.20" >> $GITHUB_ENV

      - name: Determine Gradle Version for Java 21 and greater
        id: determine-gradle 21gr
        if: matrix.java-version >= 21
        run: echo "gradle-version=8.5" >> $GITHUB_ENV

      - name: Determine Gradle Version for Java 20 and lower
        id: determine-gradle 21lw
        if: matrix.java-version < 21
        run: echo "gradle-version=7.4.2" >> $GITHUB_ENV

      - name: Set-up Gradle ${{ env.gradle-version }}
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: ${{ env.gradle-version }}

      - name: Run tests with version filtering
        run: gradle test
