name: Compatibility Matrix Tests

on:
  workflow_dispatch:
    inputs:
      os:
        description: 'Operating System (linux-latest, windows-latest, macos-latest)'
        required: true
        default: 'linux-latest'
      java:
        description: 'Java version (8, 11, 17, 21)'
        required: true
        default: '17'
      ignoreTests:
        description: 'Ignore tests (websockets, test-frameworks, ...)'
        required: false
jobs:
  tests:
    runs-on: ${{ github.event.inputs.os }}
    steps:
      - name: Set up Java ${{ github.event.inputs.java }}
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: ${{ github.event.inputs.java }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Determine Gradle Version for Java 21 and greater
        if: matrix.java-version >= 21
        run: echo "gradle-version=8.5" >> $GITHUB_ENV

      - name: Determine Gradle Version for Java 20 and lower
        if: matrix.java-version < 21
        run: echo "gradle-version=7.4.2" >> $GITHUB_ENV

      - name: Set-up Gradle ${{ env.gradle-version }}
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: ${{ env.gradle-version }}
          add-job-summary: 'on-failure'

      - name: Run tests
        env:
          ignoreTests: ${{ github.event.inputs.ignoreTests }}
        run: gradle test

      - name: Test Report (Linux)
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: startsWith(github.event.inputs.os, 'ubuntu-') && (success() || failure())
        with:
          check_name: Test Report (${{ matrix.os}},${{ matrix.java-version}})
          files: |
            tests/**/build/test-results/test/TEST-*.xml

      - name: Test Report (Windows)
        uses: EnricoMi/publish-unit-test-result-action/windows@v2
        if: startsWith(github.event.inputs.os, 'windows-') && (success() || failure())
        with:
          check_name: Test Report (${{ matrix.os}},${{ matrix.java-version}})
          files: |
            tests/**/build/test-results/test/TEST-*.xml                      

      - name: Test Report (MacOS)
        uses: EnricoMi/publish-unit-test-result-action/macos@v2
        if: startsWith(github.event.inputs.os, 'macos-') && (success() || failure())
        with:
          check_name: Test Report (${{ matrix.os}},${{ matrix.java-version}})
          files: |
            tests/**/build/test-results/test/TEST-*.xml

#      - name: Upload aggregated test report
#        uses: actions/upload-artifact@v4
#        if: success() || failure()
#        with:
#          name: aggregated-results-${{ matrix.os }}-java${{ matrix.java-version }}
#          path: build/reports/tests/unit-test/aggregated-results/
